package UMLEditor.model;

/**
 * Created by beltre on 10/25/16.
 */
public enum State {
    LINE, CLASSBOX, SELECT, ASSOCIATION, GENERALIZATION, IMPLEMENTATION, AGGREGATION, COMPOSITION, DEPENDENCY
}
